ci:
    autofix_prs: false
    autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.10"
    hooks:
      - id: ruff-format
      - id: ruff
        # args: [ --fix ]
        # args: [ --fix, --unsafe-fixes ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy