name: pygeoops-dev
channels:
  - conda-forge
dependencies:
  - python =3.12
  # required
  - geopandas-base >=0.12.1
  - numpy
  - pyproj
  - shapely >1
  - topojson
  # optional
  - simplification
  # benchmark
  #- geofileops
  - pandas
  - pandas-stubs
  # testing
  - matplotlib
  - pytest
  - pytest-cov
  # linting
  - mypy ==1.18.2
  - pre-commit
  - ruff ==0.13.3
