name: pygeoops-dev
channels:
  - conda-forge
dependencies:
  - python =3.10
  - pip
  # required
  - geopandas-base
  - shapely >1
  - topojson
  # benchmark
  - geofileops
  - pandas
  - pandas-stubs
  # testing
  - matplotlib
  - pytest
  - pytest-cov
  # linting
  - black
  - mypy
  - pre-commit
  - ruff
  # docs
  # Restrict sphinx version to < 6 to avoid logo error
  - sphinx <6
  - pydata-sphinx-theme
  - pip:
    - sphinx-automodapi ==0.13
    - simplification  # optional dependency
