name: pygeoops-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # required
  - geopandas-base>=0.12.1
  - numpy
  - pyproj
  - shapely>1
  - topojson
  # optional
  - simplification
  # benchmark
  #- geofileops
  - pandas
  - pandas-stubs
  # testing
  - matplotlib
  - pytest
  - pytest-cov
  # linting
  - mypy==1.15.0
  - pre-commit
  - ruff==0.9.10
  # docs
  # Restrict sphinx version to < 6 to avoid logo error
  - sphinx<6
  - pydata-sphinx-theme
  - pip:
    - sphinx-automodapi==0.13
